name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      
      - name: Install dependencies
        run: yarn install
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 60
          browser: chrome
          record: false
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
